services:
    controller.owner_controller:
        class: CarRegistry\ApiBundle\Controller\OwnerController
        arguments: [ @dao.owner_dao, @json_decoder ]

    dao.owner_dao:
        class: CarRegistry\ApiBundle\DAO\OwnerDAO
        arguments: [ @doctrine.orm.default_entity_manager ]

    json_decoder:
        class: CarRegistry\ApiBundle\JsonDecoder

    exception_handler_interceptor:
        class: CarRegistry\ApiBundle\ExceptionHandler\ExceptionHandlerInterceptor
        arguments: [@annotation_reader, @service_container]

    exception_handler_pointcut:
        class: CarRegistry\ApiBundle\ExceptionHandler\AllControllerPointcut
        tags:
            - { name: jms_aop.pointcut, interceptor: exception_handler_interceptor }
